// GENERATED CODE -- DO NOT EDIT!

// package: assistant_api
// file: assistant-api.proto

import * as assistant_api_pb from "./assistant-api_pb";
import * as common_pb from "./common_pb";
import * as assistant_tool_pb from "./assistant-tool_pb";
import * as assistant_analysis_pb from "./assistant-analysis_pb";
import * as assistant_webhook_pb from "./assistant-webhook_pb";
import * as assistant_knowledge_pb from "./assistant-knowledge_pb";
import * as assistant_provider_pb from "./assistant-provider_pb";
import * as grpc from "grpc";

interface IAssistantServiceService extends grpc.ServiceDefinition<grpc.UntypedServiceImplementation> {
  getAssistant: grpc.MethodDefinition<assistant_api_pb.GetAssistantRequest, assistant_api_pb.GetAssistantResponse>;
  getAllAssistant: grpc.MethodDefinition<assistant_api_pb.GetAllAssistantRequest, assistant_api_pb.GetAllAssistantResponse>;
  createAssistant: grpc.MethodDefinition<assistant_api_pb.CreateAssistantRequest, assistant_api_pb.GetAssistantResponse>;
  deleteAssistant: grpc.MethodDefinition<assistant_api_pb.DeleteAssistantRequest, assistant_api_pb.GetAssistantResponse>;
  getAllAssistantProvider: grpc.MethodDefinition<assistant_provider_pb.GetAllAssistantProviderRequest, assistant_provider_pb.GetAllAssistantProviderResponse>;
  createAssistantProvider: grpc.MethodDefinition<assistant_provider_pb.CreateAssistantProviderRequest, assistant_provider_pb.GetAssistantProviderResponse>;
  createAssistantTag: grpc.MethodDefinition<assistant_api_pb.CreateAssistantTagRequest, assistant_api_pb.GetAssistantResponse>;
  updateAssistantVersion: grpc.MethodDefinition<assistant_provider_pb.UpdateAssistantVersionRequest, assistant_api_pb.GetAssistantResponse>;
  updateAssistantDetail: grpc.MethodDefinition<assistant_api_pb.UpdateAssistantDetailRequest, assistant_api_pb.GetAssistantResponse>;
  getAllAssistantMessage: grpc.MethodDefinition<assistant_api_pb.GetAllAssistantMessageRequest, assistant_api_pb.GetAllAssistantMessageResponse>;
  getAllConversationMessage: grpc.MethodDefinition<common_pb.GetAllConversationMessageRequest, common_pb.GetAllConversationMessageResponse>;
  getAllMessage: grpc.MethodDefinition<assistant_api_pb.GetAllMessageRequest, assistant_api_pb.GetAllMessageResponse>;
  getAllAssistantTelemetry: grpc.MethodDefinition<assistant_api_pb.GetAllAssistantTelemetryRequest, assistant_api_pb.GetAllAssistantTelemetryResponse>;
  getAssistantTelemetryProvider: grpc.MethodDefinition<assistant_api_pb.GetAssistantTelemetryProviderRequest, assistant_api_pb.GetAssistantTelemetryProviderResponse>;
  getAllAssistantTelemetryProvider: grpc.MethodDefinition<assistant_api_pb.GetAllAssistantTelemetryProviderRequest, assistant_api_pb.GetAllAssistantTelemetryProviderResponse>;
  createAssistantTelemetryProvider: grpc.MethodDefinition<assistant_api_pb.CreateAssistantTelemetryProviderRequest, assistant_api_pb.GetAssistantTelemetryProviderResponse>;
  updateAssistantTelemetryProvider: grpc.MethodDefinition<assistant_api_pb.UpdateAssistantTelemetryProviderRequest, assistant_api_pb.GetAssistantTelemetryProviderResponse>;
  deleteAssistantTelemetryProvider: grpc.MethodDefinition<assistant_api_pb.DeleteAssistantTelemetryProviderRequest, assistant_api_pb.GetAssistantTelemetryProviderResponse>;
  createAssistantAuthentication: grpc.MethodDefinition<assistant_api_pb.CreateAssistantAuthenticationRequest, assistant_api_pb.GetAssistantAuthenticationResponse>;
  getAssistantAuthentication: grpc.MethodDefinition<assistant_api_pb.GetAssistantAuthenticationRequest, assistant_api_pb.GetAssistantAuthenticationResponse>;
  disableAssistantAuthentication: grpc.MethodDefinition<assistant_api_pb.DisableAssistantAuthenticationRequest, assistant_api_pb.GetAssistantAuthenticationResponse>;
  getAllAssistantConversation: grpc.MethodDefinition<common_pb.GetAllAssistantConversationRequest, common_pb.GetAllAssistantConversationResponse>;
  getAssistantConversation: grpc.MethodDefinition<assistant_api_pb.GetAssistantConversationRequest, assistant_api_pb.GetAssistantConversationResponse>;
  getAssistantHTTPLog: grpc.MethodDefinition<assistant_webhook_pb.GetAssistantHTTPLogRequest, assistant_webhook_pb.GetAssistantHTTPLogResponse>;
  getAllAssistantHTTPLog: grpc.MethodDefinition<assistant_webhook_pb.GetAllAssistantHTTPLogRequest, assistant_webhook_pb.GetAllAssistantHTTPLogResponse>;
  retryAssistantHTTPLog: grpc.MethodDefinition<assistant_webhook_pb.RetryAssistantHTTPLogRequest, assistant_webhook_pb.GetAssistantHTTPLogResponse>;
  getAllAssistantWebhook: grpc.MethodDefinition<assistant_webhook_pb.GetAllAssistantWebhookRequest, assistant_webhook_pb.GetAllAssistantWebhookResponse>;
  getAssistantWebhook: grpc.MethodDefinition<assistant_webhook_pb.GetAssistantWebhookRequest, assistant_webhook_pb.GetAssistantWebhookResponse>;
  createAssistantWebhook: grpc.MethodDefinition<assistant_webhook_pb.CreateAssistantWebhookRequest, assistant_webhook_pb.GetAssistantWebhookResponse>;
  updateAssistantWebhook: grpc.MethodDefinition<assistant_webhook_pb.UpdateAssistantWebhookRequest, assistant_webhook_pb.GetAssistantWebhookResponse>;
  deleteAssistantWebhook: grpc.MethodDefinition<assistant_webhook_pb.DeleteAssistantWebhookRequest, assistant_webhook_pb.GetAssistantWebhookResponse>;
  getAssistantToolLog: grpc.MethodDefinition<assistant_tool_pb.GetAssistantToolLogRequest, assistant_tool_pb.GetAssistantToolLogResponse>;
  getAllAssistantToolLog: grpc.MethodDefinition<assistant_tool_pb.GetAllAssistantToolLogRequest, assistant_tool_pb.GetAllAssistantToolLogResponse>;
  getAssistantAnalysis: grpc.MethodDefinition<assistant_analysis_pb.GetAssistantAnalysisRequest, assistant_analysis_pb.GetAssistantAnalysisResponse>;
  updateAssistantAnalysis: grpc.MethodDefinition<assistant_analysis_pb.UpdateAssistantAnalysisRequest, assistant_analysis_pb.GetAssistantAnalysisResponse>;
  createAssistantAnalysis: grpc.MethodDefinition<assistant_analysis_pb.CreateAssistantAnalysisRequest, assistant_analysis_pb.GetAssistantAnalysisResponse>;
  deleteAssistantAnalysis: grpc.MethodDefinition<assistant_analysis_pb.DeleteAssistantAnalysisRequest, assistant_analysis_pb.GetAssistantAnalysisResponse>;
  getAllAssistantAnalysis: grpc.MethodDefinition<assistant_analysis_pb.GetAllAssistantAnalysisRequest, assistant_analysis_pb.GetAllAssistantAnalysisResponse>;
  createAssistantTool: grpc.MethodDefinition<assistant_tool_pb.CreateAssistantToolRequest, assistant_tool_pb.GetAssistantToolResponse>;
  getAssistantTool: grpc.MethodDefinition<assistant_tool_pb.GetAssistantToolRequest, assistant_tool_pb.GetAssistantToolResponse>;
  getAllAssistantTool: grpc.MethodDefinition<assistant_tool_pb.GetAllAssistantToolRequest, assistant_tool_pb.GetAllAssistantToolResponse>;
  deleteAssistantTool: grpc.MethodDefinition<assistant_tool_pb.DeleteAssistantToolRequest, assistant_tool_pb.GetAssistantToolResponse>;
  updateAssistantTool: grpc.MethodDefinition<assistant_tool_pb.UpdateAssistantToolRequest, assistant_tool_pb.GetAssistantToolResponse>;
  createAssistantKnowledge: grpc.MethodDefinition<assistant_knowledge_pb.CreateAssistantKnowledgeRequest, assistant_knowledge_pb.GetAssistantKnowledgeResponse>;
  getAssistantKnowledge: grpc.MethodDefinition<assistant_knowledge_pb.GetAssistantKnowledgeRequest, assistant_knowledge_pb.GetAssistantKnowledgeResponse>;
  getAllAssistantKnowledge: grpc.MethodDefinition<assistant_knowledge_pb.GetAllAssistantKnowledgeRequest, assistant_knowledge_pb.GetAllAssistantKnowledgeResponse>;
  deleteAssistantKnowledge: grpc.MethodDefinition<assistant_knowledge_pb.DeleteAssistantKnowledgeRequest, assistant_knowledge_pb.GetAssistantKnowledgeResponse>;
  updateAssistantKnowledge: grpc.MethodDefinition<assistant_knowledge_pb.UpdateAssistantKnowledgeRequest, assistant_knowledge_pb.GetAssistantKnowledgeResponse>;
}

export const AssistantServiceService: IAssistantServiceService;

export interface IAssistantServiceServer extends grpc.UntypedServiceImplementation {
  getAssistant: grpc.handleUnaryCall<assistant_api_pb.GetAssistantRequest, assistant_api_pb.GetAssistantResponse>;
  getAllAssistant: grpc.handleUnaryCall<assistant_api_pb.GetAllAssistantRequest, assistant_api_pb.GetAllAssistantResponse>;
  createAssistant: grpc.handleUnaryCall<assistant_api_pb.CreateAssistantRequest, assistant_api_pb.GetAssistantResponse>;
  deleteAssistant: grpc.handleUnaryCall<assistant_api_pb.DeleteAssistantRequest, assistant_api_pb.GetAssistantResponse>;
  getAllAssistantProvider: grpc.handleUnaryCall<assistant_provider_pb.GetAllAssistantProviderRequest, assistant_provider_pb.GetAllAssistantProviderResponse>;
  createAssistantProvider: grpc.handleUnaryCall<assistant_provider_pb.CreateAssistantProviderRequest, assistant_provider_pb.GetAssistantProviderResponse>;
  createAssistantTag: grpc.handleUnaryCall<assistant_api_pb.CreateAssistantTagRequest, assistant_api_pb.GetAssistantResponse>;
  updateAssistantVersion: grpc.handleUnaryCall<assistant_provider_pb.UpdateAssistantVersionRequest, assistant_api_pb.GetAssistantResponse>;
  updateAssistantDetail: grpc.handleUnaryCall<assistant_api_pb.UpdateAssistantDetailRequest, assistant_api_pb.GetAssistantResponse>;
  getAllAssistantMessage: grpc.handleUnaryCall<assistant_api_pb.GetAllAssistantMessageRequest, assistant_api_pb.GetAllAssistantMessageResponse>;
  getAllConversationMessage: grpc.handleUnaryCall<common_pb.GetAllConversationMessageRequest, common_pb.GetAllConversationMessageResponse>;
  getAllMessage: grpc.handleUnaryCall<assistant_api_pb.GetAllMessageRequest, assistant_api_pb.GetAllMessageResponse>;
  getAllAssistantTelemetry: grpc.handleUnaryCall<assistant_api_pb.GetAllAssistantTelemetryRequest, assistant_api_pb.GetAllAssistantTelemetryResponse>;
  getAssistantTelemetryProvider: grpc.handleUnaryCall<assistant_api_pb.GetAssistantTelemetryProviderRequest, assistant_api_pb.GetAssistantTelemetryProviderResponse>;
  getAllAssistantTelemetryProvider: grpc.handleUnaryCall<assistant_api_pb.GetAllAssistantTelemetryProviderRequest, assistant_api_pb.GetAllAssistantTelemetryProviderResponse>;
  createAssistantTelemetryProvider: grpc.handleUnaryCall<assistant_api_pb.CreateAssistantTelemetryProviderRequest, assistant_api_pb.GetAssistantTelemetryProviderResponse>;
  updateAssistantTelemetryProvider: grpc.handleUnaryCall<assistant_api_pb.UpdateAssistantTelemetryProviderRequest, assistant_api_pb.GetAssistantTelemetryProviderResponse>;
  deleteAssistantTelemetryProvider: grpc.handleUnaryCall<assistant_api_pb.DeleteAssistantTelemetryProviderRequest, assistant_api_pb.GetAssistantTelemetryProviderResponse>;
  createAssistantAuthentication: grpc.handleUnaryCall<assistant_api_pb.CreateAssistantAuthenticationRequest, assistant_api_pb.GetAssistantAuthenticationResponse>;
  getAssistantAuthentication: grpc.handleUnaryCall<assistant_api_pb.GetAssistantAuthenticationRequest, assistant_api_pb.GetAssistantAuthenticationResponse>;
  disableAssistantAuthentication: grpc.handleUnaryCall<assistant_api_pb.DisableAssistantAuthenticationRequest, assistant_api_pb.GetAssistantAuthenticationResponse>;
  getAllAssistantConversation: grpc.handleUnaryCall<common_pb.GetAllAssistantConversationRequest, common_pb.GetAllAssistantConversationResponse>;
  getAssistantConversation: grpc.handleUnaryCall<assistant_api_pb.GetAssistantConversationRequest, assistant_api_pb.GetAssistantConversationResponse>;
  getAssistantHTTPLog: grpc.handleUnaryCall<assistant_webhook_pb.GetAssistantHTTPLogRequest, assistant_webhook_pb.GetAssistantHTTPLogResponse>;
  getAllAssistantHTTPLog: grpc.handleUnaryCall<assistant_webhook_pb.GetAllAssistantHTTPLogRequest, assistant_webhook_pb.GetAllAssistantHTTPLogResponse>;
  retryAssistantHTTPLog: grpc.handleUnaryCall<assistant_webhook_pb.RetryAssistantHTTPLogRequest, assistant_webhook_pb.GetAssistantHTTPLogResponse>;
  getAllAssistantWebhook: grpc.handleUnaryCall<assistant_webhook_pb.GetAllAssistantWebhookRequest, assistant_webhook_pb.GetAllAssistantWebhookResponse>;
  getAssistantWebhook: grpc.handleUnaryCall<assistant_webhook_pb.GetAssistantWebhookRequest, assistant_webhook_pb.GetAssistantWebhookResponse>;
  createAssistantWebhook: grpc.handleUnaryCall<assistant_webhook_pb.CreateAssistantWebhookRequest, assistant_webhook_pb.GetAssistantWebhookResponse>;
  updateAssistantWebhook: grpc.handleUnaryCall<assistant_webhook_pb.UpdateAssistantWebhookRequest, assistant_webhook_pb.GetAssistantWebhookResponse>;
  deleteAssistantWebhook: grpc.handleUnaryCall<assistant_webhook_pb.DeleteAssistantWebhookRequest, assistant_webhook_pb.GetAssistantWebhookResponse>;
  getAssistantToolLog: grpc.handleUnaryCall<assistant_tool_pb.GetAssistantToolLogRequest, assistant_tool_pb.GetAssistantToolLogResponse>;
  getAllAssistantToolLog: grpc.handleUnaryCall<assistant_tool_pb.GetAllAssistantToolLogRequest, assistant_tool_pb.GetAllAssistantToolLogResponse>;
  getAssistantAnalysis: grpc.handleUnaryCall<assistant_analysis_pb.GetAssistantAnalysisRequest, assistant_analysis_pb.GetAssistantAnalysisResponse>;
  updateAssistantAnalysis: grpc.handleUnaryCall<assistant_analysis_pb.UpdateAssistantAnalysisRequest, assistant_analysis_pb.GetAssistantAnalysisResponse>;
  createAssistantAnalysis: grpc.handleUnaryCall<assistant_analysis_pb.CreateAssistantAnalysisRequest, assistant_analysis_pb.GetAssistantAnalysisResponse>;
  deleteAssistantAnalysis: grpc.handleUnaryCall<assistant_analysis_pb.DeleteAssistantAnalysisRequest, assistant_analysis_pb.GetAssistantAnalysisResponse>;
  getAllAssistantAnalysis: grpc.handleUnaryCall<assistant_analysis_pb.GetAllAssistantAnalysisRequest, assistant_analysis_pb.GetAllAssistantAnalysisResponse>;
  createAssistantTool: grpc.handleUnaryCall<assistant_tool_pb.CreateAssistantToolRequest, assistant_tool_pb.GetAssistantToolResponse>;
  getAssistantTool: grpc.handleUnaryCall<assistant_tool_pb.GetAssistantToolRequest, assistant_tool_pb.GetAssistantToolResponse>;
  getAllAssistantTool: grpc.handleUnaryCall<assistant_tool_pb.GetAllAssistantToolRequest, assistant_tool_pb.GetAllAssistantToolResponse>;
  deleteAssistantTool: grpc.handleUnaryCall<assistant_tool_pb.DeleteAssistantToolRequest, assistant_tool_pb.GetAssistantToolResponse>;
  updateAssistantTool: grpc.handleUnaryCall<assistant_tool_pb.UpdateAssistantToolRequest, assistant_tool_pb.GetAssistantToolResponse>;
  createAssistantKnowledge: grpc.handleUnaryCall<assistant_knowledge_pb.CreateAssistantKnowledgeRequest, assistant_knowledge_pb.GetAssistantKnowledgeResponse>;
  getAssistantKnowledge: grpc.handleUnaryCall<assistant_knowledge_pb.GetAssistantKnowledgeRequest, assistant_knowledge_pb.GetAssistantKnowledgeResponse>;
  getAllAssistantKnowledge: grpc.handleUnaryCall<assistant_knowledge_pb.GetAllAssistantKnowledgeRequest, assistant_knowledge_pb.GetAllAssistantKnowledgeResponse>;
  deleteAssistantKnowledge: grpc.handleUnaryCall<assistant_knowledge_pb.DeleteAssistantKnowledgeRequest, assistant_knowledge_pb.GetAssistantKnowledgeResponse>;
  updateAssistantKnowledge: grpc.handleUnaryCall<assistant_knowledge_pb.UpdateAssistantKnowledgeRequest, assistant_knowledge_pb.GetAssistantKnowledgeResponse>;
}

export class AssistantServiceClient extends grpc.Client {
  constructor(address: string, credentials: grpc.ChannelCredentials, options?: object);
  getAssistant(argument: assistant_api_pb.GetAssistantRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  getAssistant(argument: assistant_api_pb.GetAssistantRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  getAssistant(argument: assistant_api_pb.GetAssistantRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  getAllAssistant(argument: assistant_api_pb.GetAllAssistantRequest, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantResponse>): grpc.ClientUnaryCall;
  getAllAssistant(argument: assistant_api_pb.GetAllAssistantRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantResponse>): grpc.ClientUnaryCall;
  getAllAssistant(argument: assistant_api_pb.GetAllAssistantRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantResponse>): grpc.ClientUnaryCall;
  createAssistant(argument: assistant_api_pb.CreateAssistantRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  createAssistant(argument: assistant_api_pb.CreateAssistantRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  createAssistant(argument: assistant_api_pb.CreateAssistantRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  deleteAssistant(argument: assistant_api_pb.DeleteAssistantRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  deleteAssistant(argument: assistant_api_pb.DeleteAssistantRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  deleteAssistant(argument: assistant_api_pb.DeleteAssistantRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  getAllAssistantProvider(argument: assistant_provider_pb.GetAllAssistantProviderRequest, callback: grpc.requestCallback<assistant_provider_pb.GetAllAssistantProviderResponse>): grpc.ClientUnaryCall;
  getAllAssistantProvider(argument: assistant_provider_pb.GetAllAssistantProviderRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_provider_pb.GetAllAssistantProviderResponse>): grpc.ClientUnaryCall;
  getAllAssistantProvider(argument: assistant_provider_pb.GetAllAssistantProviderRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_provider_pb.GetAllAssistantProviderResponse>): grpc.ClientUnaryCall;
  createAssistantProvider(argument: assistant_provider_pb.CreateAssistantProviderRequest, callback: grpc.requestCallback<assistant_provider_pb.GetAssistantProviderResponse>): grpc.ClientUnaryCall;
  createAssistantProvider(argument: assistant_provider_pb.CreateAssistantProviderRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_provider_pb.GetAssistantProviderResponse>): grpc.ClientUnaryCall;
  createAssistantProvider(argument: assistant_provider_pb.CreateAssistantProviderRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_provider_pb.GetAssistantProviderResponse>): grpc.ClientUnaryCall;
  createAssistantTag(argument: assistant_api_pb.CreateAssistantTagRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  createAssistantTag(argument: assistant_api_pb.CreateAssistantTagRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  createAssistantTag(argument: assistant_api_pb.CreateAssistantTagRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  updateAssistantVersion(argument: assistant_provider_pb.UpdateAssistantVersionRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  updateAssistantVersion(argument: assistant_provider_pb.UpdateAssistantVersionRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  updateAssistantVersion(argument: assistant_provider_pb.UpdateAssistantVersionRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  updateAssistantDetail(argument: assistant_api_pb.UpdateAssistantDetailRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  updateAssistantDetail(argument: assistant_api_pb.UpdateAssistantDetailRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  updateAssistantDetail(argument: assistant_api_pb.UpdateAssistantDetailRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantResponse>): grpc.ClientUnaryCall;
  getAllAssistantMessage(argument: assistant_api_pb.GetAllAssistantMessageRequest, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantMessageResponse>): grpc.ClientUnaryCall;
  getAllAssistantMessage(argument: assistant_api_pb.GetAllAssistantMessageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantMessageResponse>): grpc.ClientUnaryCall;
  getAllAssistantMessage(argument: assistant_api_pb.GetAllAssistantMessageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantMessageResponse>): grpc.ClientUnaryCall;
  getAllConversationMessage(argument: common_pb.GetAllConversationMessageRequest, callback: grpc.requestCallback<common_pb.GetAllConversationMessageResponse>): grpc.ClientUnaryCall;
  getAllConversationMessage(argument: common_pb.GetAllConversationMessageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<common_pb.GetAllConversationMessageResponse>): grpc.ClientUnaryCall;
  getAllConversationMessage(argument: common_pb.GetAllConversationMessageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<common_pb.GetAllConversationMessageResponse>): grpc.ClientUnaryCall;
  getAllMessage(argument: assistant_api_pb.GetAllMessageRequest, callback: grpc.requestCallback<assistant_api_pb.GetAllMessageResponse>): grpc.ClientUnaryCall;
  getAllMessage(argument: assistant_api_pb.GetAllMessageRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllMessageResponse>): grpc.ClientUnaryCall;
  getAllMessage(argument: assistant_api_pb.GetAllMessageRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllMessageResponse>): grpc.ClientUnaryCall;
  getAllAssistantTelemetry(argument: assistant_api_pb.GetAllAssistantTelemetryRequest, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantTelemetryResponse>): grpc.ClientUnaryCall;
  getAllAssistantTelemetry(argument: assistant_api_pb.GetAllAssistantTelemetryRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantTelemetryResponse>): grpc.ClientUnaryCall;
  getAllAssistantTelemetry(argument: assistant_api_pb.GetAllAssistantTelemetryRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantTelemetryResponse>): grpc.ClientUnaryCall;
  getAssistantTelemetryProvider(argument: assistant_api_pb.GetAssistantTelemetryProviderRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  getAssistantTelemetryProvider(argument: assistant_api_pb.GetAssistantTelemetryProviderRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  getAssistantTelemetryProvider(argument: assistant_api_pb.GetAssistantTelemetryProviderRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  getAllAssistantTelemetryProvider(argument: assistant_api_pb.GetAllAssistantTelemetryProviderRequest, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  getAllAssistantTelemetryProvider(argument: assistant_api_pb.GetAllAssistantTelemetryProviderRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  getAllAssistantTelemetryProvider(argument: assistant_api_pb.GetAllAssistantTelemetryProviderRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAllAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  createAssistantTelemetryProvider(argument: assistant_api_pb.CreateAssistantTelemetryProviderRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  createAssistantTelemetryProvider(argument: assistant_api_pb.CreateAssistantTelemetryProviderRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  createAssistantTelemetryProvider(argument: assistant_api_pb.CreateAssistantTelemetryProviderRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  updateAssistantTelemetryProvider(argument: assistant_api_pb.UpdateAssistantTelemetryProviderRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  updateAssistantTelemetryProvider(argument: assistant_api_pb.UpdateAssistantTelemetryProviderRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  updateAssistantTelemetryProvider(argument: assistant_api_pb.UpdateAssistantTelemetryProviderRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  deleteAssistantTelemetryProvider(argument: assistant_api_pb.DeleteAssistantTelemetryProviderRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  deleteAssistantTelemetryProvider(argument: assistant_api_pb.DeleteAssistantTelemetryProviderRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  deleteAssistantTelemetryProvider(argument: assistant_api_pb.DeleteAssistantTelemetryProviderRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantTelemetryProviderResponse>): grpc.ClientUnaryCall;
  createAssistantAuthentication(argument: assistant_api_pb.CreateAssistantAuthenticationRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantAuthenticationResponse>): grpc.ClientUnaryCall;
  createAssistantAuthentication(argument: assistant_api_pb.CreateAssistantAuthenticationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantAuthenticationResponse>): grpc.ClientUnaryCall;
  createAssistantAuthentication(argument: assistant_api_pb.CreateAssistantAuthenticationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantAuthenticationResponse>): grpc.ClientUnaryCall;
  getAssistantAuthentication(argument: assistant_api_pb.GetAssistantAuthenticationRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantAuthenticationResponse>): grpc.ClientUnaryCall;
  getAssistantAuthentication(argument: assistant_api_pb.GetAssistantAuthenticationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantAuthenticationResponse>): grpc.ClientUnaryCall;
  getAssistantAuthentication(argument: assistant_api_pb.GetAssistantAuthenticationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantAuthenticationResponse>): grpc.ClientUnaryCall;
  disableAssistantAuthentication(argument: assistant_api_pb.DisableAssistantAuthenticationRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantAuthenticationResponse>): grpc.ClientUnaryCall;
  disableAssistantAuthentication(argument: assistant_api_pb.DisableAssistantAuthenticationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantAuthenticationResponse>): grpc.ClientUnaryCall;
  disableAssistantAuthentication(argument: assistant_api_pb.DisableAssistantAuthenticationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantAuthenticationResponse>): grpc.ClientUnaryCall;
  getAllAssistantConversation(argument: common_pb.GetAllAssistantConversationRequest, callback: grpc.requestCallback<common_pb.GetAllAssistantConversationResponse>): grpc.ClientUnaryCall;
  getAllAssistantConversation(argument: common_pb.GetAllAssistantConversationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<common_pb.GetAllAssistantConversationResponse>): grpc.ClientUnaryCall;
  getAllAssistantConversation(argument: common_pb.GetAllAssistantConversationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<common_pb.GetAllAssistantConversationResponse>): grpc.ClientUnaryCall;
  getAssistantConversation(argument: assistant_api_pb.GetAssistantConversationRequest, callback: grpc.requestCallback<assistant_api_pb.GetAssistantConversationResponse>): grpc.ClientUnaryCall;
  getAssistantConversation(argument: assistant_api_pb.GetAssistantConversationRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantConversationResponse>): grpc.ClientUnaryCall;
  getAssistantConversation(argument: assistant_api_pb.GetAssistantConversationRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_api_pb.GetAssistantConversationResponse>): grpc.ClientUnaryCall;
  getAssistantHTTPLog(argument: assistant_webhook_pb.GetAssistantHTTPLogRequest, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantHTTPLogResponse>): grpc.ClientUnaryCall;
  getAssistantHTTPLog(argument: assistant_webhook_pb.GetAssistantHTTPLogRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantHTTPLogResponse>): grpc.ClientUnaryCall;
  getAssistantHTTPLog(argument: assistant_webhook_pb.GetAssistantHTTPLogRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantHTTPLogResponse>): grpc.ClientUnaryCall;
  getAllAssistantHTTPLog(argument: assistant_webhook_pb.GetAllAssistantHTTPLogRequest, callback: grpc.requestCallback<assistant_webhook_pb.GetAllAssistantHTTPLogResponse>): grpc.ClientUnaryCall;
  getAllAssistantHTTPLog(argument: assistant_webhook_pb.GetAllAssistantHTTPLogRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAllAssistantHTTPLogResponse>): grpc.ClientUnaryCall;
  getAllAssistantHTTPLog(argument: assistant_webhook_pb.GetAllAssistantHTTPLogRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAllAssistantHTTPLogResponse>): grpc.ClientUnaryCall;
  retryAssistantHTTPLog(argument: assistant_webhook_pb.RetryAssistantHTTPLogRequest, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantHTTPLogResponse>): grpc.ClientUnaryCall;
  retryAssistantHTTPLog(argument: assistant_webhook_pb.RetryAssistantHTTPLogRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantHTTPLogResponse>): grpc.ClientUnaryCall;
  retryAssistantHTTPLog(argument: assistant_webhook_pb.RetryAssistantHTTPLogRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantHTTPLogResponse>): grpc.ClientUnaryCall;
  getAllAssistantWebhook(argument: assistant_webhook_pb.GetAllAssistantWebhookRequest, callback: grpc.requestCallback<assistant_webhook_pb.GetAllAssistantWebhookResponse>): grpc.ClientUnaryCall;
  getAllAssistantWebhook(argument: assistant_webhook_pb.GetAllAssistantWebhookRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAllAssistantWebhookResponse>): grpc.ClientUnaryCall;
  getAllAssistantWebhook(argument: assistant_webhook_pb.GetAllAssistantWebhookRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAllAssistantWebhookResponse>): grpc.ClientUnaryCall;
  getAssistantWebhook(argument: assistant_webhook_pb.GetAssistantWebhookRequest, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  getAssistantWebhook(argument: assistant_webhook_pb.GetAssistantWebhookRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  getAssistantWebhook(argument: assistant_webhook_pb.GetAssistantWebhookRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  createAssistantWebhook(argument: assistant_webhook_pb.CreateAssistantWebhookRequest, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  createAssistantWebhook(argument: assistant_webhook_pb.CreateAssistantWebhookRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  createAssistantWebhook(argument: assistant_webhook_pb.CreateAssistantWebhookRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  updateAssistantWebhook(argument: assistant_webhook_pb.UpdateAssistantWebhookRequest, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  updateAssistantWebhook(argument: assistant_webhook_pb.UpdateAssistantWebhookRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  updateAssistantWebhook(argument: assistant_webhook_pb.UpdateAssistantWebhookRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  deleteAssistantWebhook(argument: assistant_webhook_pb.DeleteAssistantWebhookRequest, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  deleteAssistantWebhook(argument: assistant_webhook_pb.DeleteAssistantWebhookRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  deleteAssistantWebhook(argument: assistant_webhook_pb.DeleteAssistantWebhookRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_webhook_pb.GetAssistantWebhookResponse>): grpc.ClientUnaryCall;
  getAssistantToolLog(argument: assistant_tool_pb.GetAssistantToolLogRequest, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolLogResponse>): grpc.ClientUnaryCall;
  getAssistantToolLog(argument: assistant_tool_pb.GetAssistantToolLogRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolLogResponse>): grpc.ClientUnaryCall;
  getAssistantToolLog(argument: assistant_tool_pb.GetAssistantToolLogRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolLogResponse>): grpc.ClientUnaryCall;
  getAllAssistantToolLog(argument: assistant_tool_pb.GetAllAssistantToolLogRequest, callback: grpc.requestCallback<assistant_tool_pb.GetAllAssistantToolLogResponse>): grpc.ClientUnaryCall;
  getAllAssistantToolLog(argument: assistant_tool_pb.GetAllAssistantToolLogRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAllAssistantToolLogResponse>): grpc.ClientUnaryCall;
  getAllAssistantToolLog(argument: assistant_tool_pb.GetAllAssistantToolLogRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAllAssistantToolLogResponse>): grpc.ClientUnaryCall;
  getAssistantAnalysis(argument: assistant_analysis_pb.GetAssistantAnalysisRequest, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  getAssistantAnalysis(argument: assistant_analysis_pb.GetAssistantAnalysisRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  getAssistantAnalysis(argument: assistant_analysis_pb.GetAssistantAnalysisRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  updateAssistantAnalysis(argument: assistant_analysis_pb.UpdateAssistantAnalysisRequest, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  updateAssistantAnalysis(argument: assistant_analysis_pb.UpdateAssistantAnalysisRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  updateAssistantAnalysis(argument: assistant_analysis_pb.UpdateAssistantAnalysisRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  createAssistantAnalysis(argument: assistant_analysis_pb.CreateAssistantAnalysisRequest, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  createAssistantAnalysis(argument: assistant_analysis_pb.CreateAssistantAnalysisRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  createAssistantAnalysis(argument: assistant_analysis_pb.CreateAssistantAnalysisRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  deleteAssistantAnalysis(argument: assistant_analysis_pb.DeleteAssistantAnalysisRequest, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  deleteAssistantAnalysis(argument: assistant_analysis_pb.DeleteAssistantAnalysisRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  deleteAssistantAnalysis(argument: assistant_analysis_pb.DeleteAssistantAnalysisRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  getAllAssistantAnalysis(argument: assistant_analysis_pb.GetAllAssistantAnalysisRequest, callback: grpc.requestCallback<assistant_analysis_pb.GetAllAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  getAllAssistantAnalysis(argument: assistant_analysis_pb.GetAllAssistantAnalysisRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAllAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  getAllAssistantAnalysis(argument: assistant_analysis_pb.GetAllAssistantAnalysisRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_analysis_pb.GetAllAssistantAnalysisResponse>): grpc.ClientUnaryCall;
  createAssistantTool(argument: assistant_tool_pb.CreateAssistantToolRequest, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  createAssistantTool(argument: assistant_tool_pb.CreateAssistantToolRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  createAssistantTool(argument: assistant_tool_pb.CreateAssistantToolRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  getAssistantTool(argument: assistant_tool_pb.GetAssistantToolRequest, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  getAssistantTool(argument: assistant_tool_pb.GetAssistantToolRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  getAssistantTool(argument: assistant_tool_pb.GetAssistantToolRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  getAllAssistantTool(argument: assistant_tool_pb.GetAllAssistantToolRequest, callback: grpc.requestCallback<assistant_tool_pb.GetAllAssistantToolResponse>): grpc.ClientUnaryCall;
  getAllAssistantTool(argument: assistant_tool_pb.GetAllAssistantToolRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAllAssistantToolResponse>): grpc.ClientUnaryCall;
  getAllAssistantTool(argument: assistant_tool_pb.GetAllAssistantToolRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAllAssistantToolResponse>): grpc.ClientUnaryCall;
  deleteAssistantTool(argument: assistant_tool_pb.DeleteAssistantToolRequest, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  deleteAssistantTool(argument: assistant_tool_pb.DeleteAssistantToolRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  deleteAssistantTool(argument: assistant_tool_pb.DeleteAssistantToolRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  updateAssistantTool(argument: assistant_tool_pb.UpdateAssistantToolRequest, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  updateAssistantTool(argument: assistant_tool_pb.UpdateAssistantToolRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  updateAssistantTool(argument: assistant_tool_pb.UpdateAssistantToolRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_tool_pb.GetAssistantToolResponse>): grpc.ClientUnaryCall;
  createAssistantKnowledge(argument: assistant_knowledge_pb.CreateAssistantKnowledgeRequest, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  createAssistantKnowledge(argument: assistant_knowledge_pb.CreateAssistantKnowledgeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  createAssistantKnowledge(argument: assistant_knowledge_pb.CreateAssistantKnowledgeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  getAssistantKnowledge(argument: assistant_knowledge_pb.GetAssistantKnowledgeRequest, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  getAssistantKnowledge(argument: assistant_knowledge_pb.GetAssistantKnowledgeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  getAssistantKnowledge(argument: assistant_knowledge_pb.GetAssistantKnowledgeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  getAllAssistantKnowledge(argument: assistant_knowledge_pb.GetAllAssistantKnowledgeRequest, callback: grpc.requestCallback<assistant_knowledge_pb.GetAllAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  getAllAssistantKnowledge(argument: assistant_knowledge_pb.GetAllAssistantKnowledgeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAllAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  getAllAssistantKnowledge(argument: assistant_knowledge_pb.GetAllAssistantKnowledgeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAllAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  deleteAssistantKnowledge(argument: assistant_knowledge_pb.DeleteAssistantKnowledgeRequest, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  deleteAssistantKnowledge(argument: assistant_knowledge_pb.DeleteAssistantKnowledgeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  deleteAssistantKnowledge(argument: assistant_knowledge_pb.DeleteAssistantKnowledgeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  updateAssistantKnowledge(argument: assistant_knowledge_pb.UpdateAssistantKnowledgeRequest, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  updateAssistantKnowledge(argument: assistant_knowledge_pb.UpdateAssistantKnowledgeRequest, metadataOrOptions: grpc.Metadata | grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
  updateAssistantKnowledge(argument: assistant_knowledge_pb.UpdateAssistantKnowledgeRequest, metadata: grpc.Metadata | null, options: grpc.CallOptions | null, callback: grpc.requestCallback<assistant_knowledge_pb.GetAssistantKnowledgeResponse>): grpc.ClientUnaryCall;
}
